name: Cucumber Tests

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run Cucumber tests and generate JUnit XML reports
      run: |
        # Replace the following command with the actual command to run your Cucumber tests
        python -m behave --junit --junit-directory=reports
      continue-on-error: true  # Continue even if tests fail to ensure the report is generated
    - name: Install junit2html
      run: |
        pip install junit2html
    - name: Convert JUnit XML to HTML for each report
      run: |
        find reports -name '*.xml' -exec sh -c 'junit2html "$0" > "${0%.xml}.html"' {} \;
    - name: Merge HTML reports
      run: |
        # Replace the following command with the actual command to merge HTML reports
        # e.g., merge-html-reports reports/*.html > merged-report.html
        echo "Command to merge reports here"
    - name: List Merged HTML report
      run: |
        ls merged-report.html
    - name: Upload Merged HTML report
      uses: actions/upload-artifact@v2
      with:
        name: junit-merged-html-report
        path: merged-report.html
