name: Cucumber Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Cucumber tests and generate JUnit XML report
      run: |
        # Replace the following command with the actual command to run your Cucumber tests
        python -m behave --junit --junit-directory=reports
      continue-on-error: true  # Continue even if tests fail to ensure the report is generated

    - name: Upload JUnit XML report
      uses: actions/upload-artifact@v2
      with:
        name: junit-reports
        path: reports