name: Cucumber Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Use Python 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Replace with the actual path to your requirements file

    - name: Run Cucumber tests
      run: |
        # Replace the following command with the actual command to run your Cucumber tests
        python -m behave